global:
  scrape_interval: 10s
  
rule_files:
  - "prometheus_rules.yml"
  - "kubernetes_rules.yml"

alerting:
  alertmanagers:
  - static_configs:
      - targets:
          - "172.30.0.3:9093"

scrape_configs:
  - job_name: dc_prometheus
    honor_labels: true
    tls_config:
      insecure_skip_verify: true
    metrics_path: '/federate'
    params:
      'match[]':
        - '{job!=""}'
    static_configs:
      - targets: ['pth.getwonder.tech']
      - targets: ['pth.newe.es']
      - targets: ['pth.plt.bipeek.es']
      - targets: ['rgmftcv.gc.syndeno.net']
      - targets: ['pth.plt.sesamelon.com']
      - targets: ['pth.plt.gc.syndeno.net']
      - targets: ['pth.plt.prezo.info']
      - targets: ['pth.plt.growpro.syndeno.io']
    basic_auth:
      username: 'admin'
      password: 'Syndeno2022!'
